/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Magaly García
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        this.setLocationRelativeTo(null);
       
      //  new CambiaPanel(panelprincipal,new generaVentas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ventas = new javax.swing.JButton();
        cortecaja = new javax.swing.JButton();
        inventario = new javax.swing.JButton();
        reportes = new javax.swing.JButton();
        adminusuarios = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelprincipal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(40, 102, 113));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 871, 70));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(42767, 42767));
        jPanel2.setMinimumSize(new java.awt.Dimension(42767, 42767));

        ventas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ventas.setForeground(new java.awt.Color(255, 255, 255));
        ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton.png"))); // NOI18N
        ventas.setText("Generar venta");
        ventas.setContentAreaFilled(false);
        ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ventas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ventas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton5.png"))); // NOI18N
        ventas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton5.png"))); // NOI18N
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });

        cortecaja.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cortecaja.setForeground(new java.awt.Color(255, 255, 255));
        cortecaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton.png"))); // NOI18N
        cortecaja.setText("Cierre de caja");
        cortecaja.setContentAreaFilled(false);
        cortecaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cortecaja.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton5.png"))); // NOI18N

        inventario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inventario.setForeground(new java.awt.Color(255, 255, 255));
        inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton.png"))); // NOI18N
        inventario.setText("Inventario");
        inventario.setContentAreaFilled(false);
        inventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton5.png"))); // NOI18N

        reportes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        reportes.setForeground(new java.awt.Color(255, 255, 255));
        reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton.png"))); // NOI18N
        reportes.setText("Reportes");
        reportes.setContentAreaFilled(false);
        reportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reportes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton5.png"))); // NOI18N

        adminusuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminusuarios.setForeground(new java.awt.Color(255, 255, 255));
        adminusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton.png"))); // NOI18N
        adminusuarios.setText("Administrar usuarios");
        adminusuarios.setContentAreaFilled(false);
        adminusuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adminusuarios.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton5.png"))); // NOI18N

        salir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        salir.setText("Salir");
        salir.setContentAreaFilled(false);
        salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton5.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Opciones de operación");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(salir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(adminusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cortecaja, javax.swing.GroupLayout.PREFERRED_SIZE, 193, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cortecaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(inventario)
                .addGap(18, 18, 18)
                .addComponent(reportes)
                .addGap(18, 18, 18)
                .addComponent(adminusuarios)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 240, 460));

        panelprincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_farmacia.png"))); // NOI18N

        javax.swing.GroupLayout panelprincipalLayout = new javax.swing.GroupLayout(panelprincipal);
        panelprincipal.setLayout(panelprincipalLayout);
        panelprincipalLayout.setHorizontalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprincipalLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(166, 166, 166))
        );
        panelprincipalLayout.setVerticalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelprincipalLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel3)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        getContentPane().add(panelprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
      //  new CambiaPanel(panelprincipal,new generaVentas());
    }//GEN-LAST:event_ventasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminusuarios;
    private javax.swing.JButton cortecaja;
    private javax.swing.JButton inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JButton reportes;
    private javax.swing.JButton salir;
    private javax.swing.JButton ventas;
    // End of variables declaration//GEN-END:variables
}
